
#pragma once
#ifndef ERROR_H_
#define ERROR_H_

#define ERROR_POINTER_IS_NULL 0
#define ERROR_FAILED_TO_ALLOCATE_MEMORY 1
#define ERROR_FAILED_TO_OPEN_FILE 2
#define ERROR_WRITING_IN_FILE 3
#define ERROR_READING_FROM_FILE 4

#define ERROR_ADDING_TASK_INTO_THE_LIST 7

#define SUCCESS 10
#define FAILURE 11
#define TASK_ADDED_SUCCESS 12

#endif